#!/bin/bash

echo "Please enter the file name here : "
read file_name


if [ -f $file_name ]
then
   if [ -w $file_name ]
   then 
      echo "Please enter something into the file,and to exit just press cltr+d"
      cat >> $file_name
   else
      echo " The file dont have the write perrmission "
   fi
else
   echo "The filedont exist"
fi
